### ISSUE TITLE
mermaid.js loaded from CDN instead of locally

### ISSUE THREAD

**Issue by RyanCoordinator** [dzello/reveal-hugo#122]
Thank you for reveal-hugo, I love it! I'm using it for https://mondays.pizza

I'm working on eliminating needless files and making sure it works offline, because I'm trying to host it on ENS/IPFS

I have found that mermaid is loading from CDN regardless of options.

(also, I expect load_default_plugins=false to exclude loading/publishing things like highlight-js, but that deserves it own issue)
Latest build log: https://builds.sr.ht/~techpizzamondays/job/859790

Am I using options wrong? Is there an easy fix to static-local include, or just simply exclude (since I'm not using it) mermaid and the other additions?

Thank you! If you can point me in the right direction, I'm willing to write a PR, I just make it a habit to touch base with maintainer devs before trying anything like that.

Thanks again for reveal-hugo!

**Comment by RyanCoordinator** [comment]
I ended up putting "rm highlight" in my build script and switching IPFS providers to get around file limits, instead of fixing this at the generator.

Anywyas, victory achieved for my overall objective!
https://techpizzamondays.eth.limo works on every computer and phone tested so far!
Thank you!

**Comment by dzello** [comment]
@RyanCoordinator Thanks for opening the issue and sorry about the slow response 😅 I'm glad you're getting value from the project! I love the domain - excellent use of the .pizza extension. I'm also glad you were able to figure this out at the build script level.

The goal _is_ to be able to turn off plugins and CDN loading so that reveal-hugo can run fully locally. At one point I know that worked, but it's possible that a regression was accidentally introduced. I would welcome a PR if it's something you wanted to take a look into. I'm happy to provide guidance and review it. New contribs are always welcome 🙏

**Comment by davidovich** [comment]
I was the original author that introduced mermaid support, and I too thought that we should add a way to have a local version. I was not sure how at the time - and still am. I can try to find a little _pleasure dev time_ this weekend, or the next :-), and see how this could be done. @dzello any pointers for a strategy in doing this is welcome.

**Comment by dzello** [comment]
@davidovich Cheers 🙏
