### ISSUE TITLE
404 when rendering presentation from leaf bundle `index.md` instead `_index.md` .

### ISSUE THREAD

**Issue by solrayc** [dzello/reveal-hugo#27]
I'm trying to create a listing page for all the presentations on my site.
Here is how I need to organize my content in order to create a list of my presentations (this is required by the theme I use):

```
content/
├── presentations
│   │
│   ├── _index.md
│   │
│   ├── my-first-presentation
│   │   ├── image1.jpg
│   │   └── index.md
│   └── my-other-presentaion
│       └── index.md
│
└── blog
```

I have all of my presentations at `presentations` branch with leaf bundles for each presentation under specialized folders.

Unfortunately, I get error 404 when opening a presentation if I organize my content this way. This happens when I use `index.md` as presentation file and not `_index.md`.
Presentation renders fine when I use `_index.md` instead of `index.md`, but then the presentation is not listed on presentaions list page, because it becomes a branch bundle with `_index.md`.

Is there a way to make revealjs work with `index.md` leaf bundles?

Thanks :)

```
hugo env

Hugo Static Site Generator v0.54.0/extended windows/amd64 BuildDate: unknown
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.11.5"
```
Theme `minimo`

**Comment by dzello** [comment]
Thanks for opening the issue. The reason no presentation was generated was because `index.md` in a leaf bundle gets looked up with the single template type instead of the list template type. reveal-hugo doesn't render single template types as it assumes they are parts of a bigger presentation (and not meant to become HTML files themselves).

Thankfully, this is easy to change by telling Hugo to use the list template in the front matter. So you can do:

```
layout = "list"
```

That should output a presentation, fixing the 404. Your other theme should still see the bundle as-is. Another thing you can do is:

**Comment by dzello** [comment]
I created an example presentation that shows how to do this also:

[exampleSite/content/bundle-example](https://github.com/dzello/reveal-hugo/tree/master/exampleSite/content/bundle-example)

Deployed at: [https://reveal-hugo.dzello.com/bundle-example/](https://reveal-hugo.dzello.com/bundle-example/).

**Comment by solrayc** [comment]
It works! 

I pulled the latest code and successfully tested both `layout = "list"` and `layout = "bundle"` in presentation front matter. 

Now I am able to automatically list all presentations that I want, just like blog posts.

Thanks so much @dzello , I deeply appreciate and value what you do!

**Comment by dzello** [comment]
Glad that it worked! 😄 The project is getting better thanks to your contributions, it's appreciated!
