### ISSUE TITLE
Code blocks are not wrapped

### ISSUE THREAD

**Issue by ssbarnea** [dzello/reveal-hugo#84]
I discovered that code blocks do not wrap, which is almost for sure not something you would desire when making a presentation.

The workaround as to add the code below to ``layouts/partials/reveal-hugo/head.html``:
```html
<style>
pre > code {
    white-space: pre-wrap;
    }
</style>
```

I did not make a PR because I think it may be a better way to do it than adding a partial but I was not sure which one was. I am also curious how can I add such an override at my site level instead of hacking the theme itself.

**Comment by dzello** [comment]
Hi @ssbarnea, normally this would be handled in the Reveal.js theme, whether it's one that it out-of-the-box or a custom theme. I am surprised that's not the default behavior but that's up to Reveal.js, not reveal-hugo.

As far as the override, that's an acceptable way to do it. Those partials exist so that they can be overridden to make small CSS / JS changes like that. Another slightly more advanced way could be to make a [custom theme](https://github.com/dzello/reveal-hugo#compiling-a-custom-revealjs-theme-with-hugo-pipes).
